// <auto-generated />
using System;
using Magnise.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Magnise.Infrastructure.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    partial class AssetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Magnise.Domain.Entities.AssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetPriceAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetPriceAssetId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("Magnise.Domain.Entities.AssetPriceEntity", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("AssetId");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetPrices", (string)null);
                });

            modelBuilder.Entity("Magnise.Domain.Entities.AssetEntity", b =>
                {
                    b.HasOne("Magnise.Domain.Entities.AssetPriceEntity", "AssetPrice")
                        .WithMany()
                        .HasForeignKey("AssetPriceAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetPrice");
                });

            modelBuilder.Entity("Magnise.Domain.Entities.AssetPriceEntity", b =>
                {
                    b.HasOne("Magnise.Domain.Entities.AssetEntity", "Asset")
                        .WithOne()
                        .HasForeignKey("Magnise.Domain.Entities.AssetPriceEntity", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });
#pragma warning restore 612, 618
        }
    }
}
